### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by shuhuiluo** [malik672/uniswap-sdk-core-rust#23]
Dependencies
```toml
rustc-hex = "2.1.0"
serde-value = "0.7.0"
sha3 = "0.10.8"
```
can be safely removed. `regex` can be removed after using `alloy-primitives` for `validate_and_parse_address`.
